spring:
  application:
    name: Spring security template
  profiles:
    active:
      - h2
#      - mysql  #when mysql
      - localhost
  liquibase:
    change-log: classpath:database/db-changelog.xml
logging:
  level:
    org.springframework: INFO


server:
  port: 9000



